# Generated by Django 3.2 on 2021-04-16 18:45

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import thumbnails.fields


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# api.migrations.0002_auto_20210415_2318


def create_default_thumbnail_sizes(apps, schema_editor):
    ThumbnailSize = apps.get_model('api', 'ThumbnailSize')
    ThumbnailSize.objects.create(width=400, height=400, pk=1)
    ThumbnailSize.objects.create(width=200, height=200, pk=2)


def create_default_account_plans(apps, schema_editor):
    ThumbnailSize = apps.get_model('api', 'ThumbnailSize')
    AccountPlan = apps.get_model('api', 'AccountPlan')
    standart_thumbnail_400x400 = ThumbnailSize.objects.get(width=400, height=400)
    standart_thumbnail_200x200 = ThumbnailSize.objects.get(width=200, height=200)

    basic = AccountPlan(name='Basic', pk=1)
    basic.save()
    basic.thumbnail_sizes.add(standart_thumbnail_200x200)

    premium = AccountPlan(name='Premium', pk=2, have_access_to_original_link=True)
    premium.save()
    premium.thumbnail_sizes.add(standart_thumbnail_200x200, standart_thumbnail_400x400)

    enterprise = AccountPlan(
        name='Enterprise', pk=3, have_access_to_original_link=True, can_create_expirable_links=True
    )
    enterprise.save()
    enterprise.thumbnail_sizes.add(standart_thumbnail_200x200, standart_thumbnail_200x200)


def delete_default_thumbnail_sizes(apps, schema_editor):
    ThumbnailSize = apps.get_model('api', 'ThumbnailSize')
    ThumbnailSize.objects.filter(pk__in=[1, 2]).delete()


def delete_default_account_plans(apps, schema_editor):
    AccountPlan = apps.get_model('api', 'AccountPlan')
    AccountPlan.objects.filter(pk__in=[1, 2, 3]).delete()


class Migration(migrations.Migration):

    replaces = [('api', '0001_initial'), ('api', '0002_auto_20210415_2318'), ('api', '0003_auto_20210415_2337'), ('api', '0004_rename_account_accountplanassignement_account_plan'), ('api', '0005_auto_20210416_1149'), ('api', '0006_alter_thumbnail_unique_together'), ('api', '0007_alter_accountplanassignement_user')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('have_access_to_original_link', models.BooleanField(default=bool)),
                ('can_create_expirable_links', models.BooleanField(default=bool)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ThumbnailSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('width', 'height')},
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', thumbnails.fields.ImageField(upload_to='')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpirableLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('experation_period', models.DurationField(validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=300)), django.core.validators.MaxValueValidator(datetime.timedelta(seconds=30000))])),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.image')),
            ],
        ),
        migrations.CreateModel(
            name='AcountPlanAssignement',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.accountplan')),
            ],
        ),
        migrations.AddField(
            model_name='accountplan',
            name='thumbnail_sizes',
            field=models.ManyToManyField(related_name='account_plans', to='api.ThumbnailSize'),
        ),
        migrations.RunPython(
            code=create_default_thumbnail_sizes,
            reverse_code=delete_default_thumbnail_sizes,
        ),
        migrations.RunPython(
            code=create_default_account_plans,
            reverse_code=delete_default_account_plans,
        ),
        migrations.CreateModel(
            name='AccountPlanAssignement',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account_plan_assignement', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('account_plan', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.accountplan')),
            ],
        ),
        migrations.DeleteModel(
            name='AcountPlanAssignement',
        ),
        migrations.AlterField(
            model_name='accountplan',
            name='can_create_expirable_links',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountplan',
            name='have_access_to_original_link',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_image', thumbnails.fields.ImageField(upload_to='')),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.image')),
                ('thumbnail_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.thumbnailsize')),
            ],
            options={
                'unique_together': {('thumbnail_size', 'original_image')},
            },
        ),
    ]
