# Generated by Django 3.2 on 2021-04-15 22:56

from django.db import migrations


def create_default_thumbnail_sizes(apps, schema_editor):
    ThumbnailSize = apps.get_model('api', 'ThumbnailSize')
    ThumbnailSize.objects.create(width=400, height=400, pk=1)
    ThumbnailSize.objects.create(width=200, height=200, pk=2)


def create_default_account_plans(apps, schema_editor):
    ThumbnailSize = apps.get_model('api', 'ThumbnailSize')
    AccountPlan = apps.get_model('api', 'AccountPlan')
    standart_thumbnail_400x400 = ThumbnailSize.objects.get(width=400, height=400)
    standart_thumbnail_200x200 = ThumbnailSize.objects.get(width=200, height=200)

    basic = AccountPlan(name='Basic', pk=1)
    basic.save()
    basic.thumbnail_sizes.add(standart_thumbnail_200x200)

    premium = AccountPlan(name='Premium', pk=2, have_access_to_original_link=True)
    premium.save()
    premium.thumbnail_sizes.add(standart_thumbnail_200x200, standart_thumbnail_400x400)

    enterprise = AccountPlan(
        name='Enterprise', pk=3, have_access_to_original_link=True, can_create_expirable_links=True
    )
    enterprise.save()
    enterprise.thumbnail_sizes.add(standart_thumbnail_200x200, standart_thumbnail_200x200)


def delete_default_thumbnail_sizes(apps, schema_editor):
    ThumbnailSize = apps.get_model('api', 'ThumbnailSize')
    ThumbnailSize.objects.filter(pk__in=[1, 2]).delete()


def delete_default_account_plans(apps, schema_editor):
    AccountPlan = apps.get_model('api', 'AccountPlan')
    AccountPlan.objects.filter(pk__in=[1, 2, 3]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_thumbnail_sizes, delete_default_thumbnail_sizes),
        migrations.RunPython(create_default_account_plans, delete_default_account_plans)
    ]
