# Generated by Django 3.2 on 2021-04-19 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_squashed_0007_alter_accountplanassignement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expirablelink',
            name='creator',
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='original_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='api.image'),
        ),
    ]
