# Generated by Django 3.2 on 2021-04-15 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0002_auto_20210415_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPlanAssignement',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('account', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.accountplan')),
            ],
        ),
        migrations.DeleteModel(
            name='AcountPlanAssignement',
        ),
    ]
