# Generated by Django 3.2 on 2021-04-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210415_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountplanassignement',
            old_name='account',
            new_name='account_plan',
        ),
    ]
