# Generated by Django 3.2 on 2021-04-16 11:49

from django.db import migrations, models
import django.db.models.deletion
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_account_accountplanassignement_account_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountplan',
            name='can_create_expirable_links',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountplan',
            name='have_access_to_original_link',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_image', thumbnails.fields.ImageField(upload_to='')),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.image')),
                ('thumbnail_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.thumbnailsize')),
            ],
        ),
    ]
