# Generated by Django 3.2 on 2021-04-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210416_1149'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thumbnail',
            unique_together={('thumbnail_size', 'original_image')},
        ),
    ]
