# Generated by Django 3.2 on 2021-04-16 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_alter_thumbnail_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountplanassignement',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account_plan_assignement', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
